language: cpp
dist: trusty
sudo: required

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - gcc-4.9
            - gcc-5
            - gcc-6
            - cmake
            - python3
            - python3-pip


env:
    global:
    - CONAN_UPLOAD=1
    - CONAN_GCC_VERSIONS="4.8,4.9,5,6"
    - CONAN_USERNAME=russelltg
    
install:
    - pip3 install conan conan_package_tools
    - sudo add-apt-repository ppa:beineri/opt-qt57-trusty -y
    - sudo apt-get update
    - sudo apt-get install qt57base qt57script qt57declarative qt57tools qt57x11extras qt57svg

script:
    - python3 ./run.py
